### ISSUE TITLE
initialised event

### ISSUE THREAD

**Issue by sylvainbaronnet** [albertogasparin/Optiscroll#24]
Hello,

It would be nice to have an on initialised event.

Is there any way to detect it currently ?

**Comment by albertogasparin** [comment]
Can you tell me what's your use case?
As Optiscroll initialisation is synchronous, the code that runs after should be able to use the api without need to wait.

**Comment by sylvainbaronnet** [comment]
ok if it's synchronous then it's not needed indeed, thanks.
