### ISSUE TITLE
Can't click and drag to scroll in Firefox 54

### ISSUE THREAD

**Issue by stuniq** [albertogasparin/Optiscroll#28]
As title says... I can't click and drag on the scrollbar in Firefox to scroll. Only the mousewheel works for vertical scrolling (horizontal scrolling is impossible without the click/drag functionality). Works fine in IE and Chrome.

Reproducible on the Optiscroll example site.

**Comment by albertogasparin** [comment]
Hi, unfortunately I cannot reproduce. Optiscroll website works fine here. Just checked on Firefox 45 & 54 (MacOS) and Firefox 54 (Win 10 VM): both horizontal and vertical scrollbars can be dragged just fine. Could you provide some more detail?

**Comment by stuniq** [comment]
It works fine here on my home laptop as well. Maybe it has something to do with my work laptop having a touch enabled screen. In that case, it might be the same issue the other guy reported. I'll try again on Monday...

**Comment by stuniq** [comment]
I believe this is the same issue as the other open issue... so I will close this one.
