### ISSUE TITLE
contentElement settings option?

### ISSUE THREAD

**Issue by Sinled** [albertogasparin/Optiscroll#30]
Hi,

while debugging strange bug in my application, i've stumbled upon this [piece of code](https://github.com/albertogasparin/Optiscroll/blob/master/src/optiscroll.js#L300)

```js
    // unwrap content
    if (!this.settings.contentElement) {
      while(child = scrollEl.childNodes[0]) {
        element.insertBefore(child, scrollEl);
      }
      element.removeChild(scrollEl);
      this.scrollEl = null;
    }
```
I'd tried to find any reference for `contentElement` but found none. 
Am i missing something or there should be check for `wrapContent`?

**Comment by Sinled** [comment]
@albertogasparin Done. Or should i also run `prepublish` and commit results?

**Comment by albertogasparin** [comment]
Thanks a lot for the PR. I merged it and published a new version with the fix.
