### ISSUE TITLE
Scroll dynamic elements

### ISSUE THREAD

**Issue by bofeiw** [albertogasparin/Optiscroll#33]
Hi this library is great! But when I try to dynamically scroll elements, it does not work.
For example, I create a Optiscroll on load, and later append some children elements into my container, but optiscroll does not handle appended children, and it seems that appended children are outside of optiscroll wrapper.

**Comment by albertogasparin** [comment]
Hi @bofeiw, could you try to reproduce an example somewhere (eg on codepen) ?
Optiscroll should handle new elements fine. Please make sure that they are added in the correct place, as Optiscroll might wrap your content with an additional `div` (so you might be adding them in the wrong place)

**Comment by bofeiw** [comment]
Just realised that I have appended new elements to wrong places(outside Optiscroll wrapper), where I should append new elements to the additional div created by Optiscroll. It works for me now. I suggest to make it clearer that new elements should go into wrapper for dynamic usage. Thanks!
