### ISSUE TITLE
Event callback

### ISSUE THREAD

**Issue by usb248** [albertogasparin/Optiscroll#34]
Hi,
Any callback for scrollIntoView end event ? Why ? I need to do some stuff after ending of scrollIntoView. (no i don't want to do an ugly setTimeout())

Thanks for your lib ! 👍

**Comment by albertogasparin** [comment]
Have you tried using the custom events that Optiscroll fires? You can bind once `scrollstop` before triggering `scrollIntoView` and that should act like a callback, fired once `scrollIntoView` has completed

**Comment by usb248** [comment]
Hmm okey I thought that this event is fired only by user interaction (like the doc mentions it). I will try it. Thanks
