### ISSUE TITLE
Can not get default Browser scroll bars to hide

### ISSUE THREAD

**Issue by ThianBrodie** [albertogasparin/Optiscroll#38]
Hi Albert

I have tried every combination to try and the hide the browsers scroll bar and show the Optiscroll track.
The Jquery wraps the code ok with the elements, could you please advise?

**Comment by albertogasparin** [comment]
Hi @ThianBrodie, unfortunately targeting `body` directly is not supported. You have to create another wrapper around your content and initialise Optiscroll on it. That is unfortunately a browser limitation due to the weird way they handle `html`/`body` scrolls for legacy reasons.

**Comment by ThianBrodie** [comment]
Hey Alberto

Thank you for you quick reply, I managed to get it working, Thank you

Thian
